-- ════════════════════════════════════════════════════════════
--  Medway & Kent Removals — Admin dashboard schema
--  Idempotent. Safe to run multiple times in the Supabase SQL editor.
-- ════════════════════════════════════════════════════════════
--
--  ⚠️  RLS WARNING — READ THIS BEFORE YOU TOUCH ROW LEVEL SECURITY  ⚠️
--
--  SUPABASE_KEY in this project is the ANON key — the SAME key the public
--  quote form on the website uses to INSERT leads (see api/quote.js).
--
--  Do NOT enable Row Level Security (RLS) on quote_requests or appointments.
--  If you switch RLS on WITHOUT also adding an anon INSERT policy, the public
--  quote form will SILENTLY STOP SAVING LEADS — no error on the site, just
--  lost enquiries. Leave RLS OFF on both tables (this is the default).
--
--  If you ever DO want RLS on, you must swap SUPABASE_KEY to the service_role
--  key for the admin functions AND add an anon INSERT policy for the public
--  form. Until then: RLS stays off.
--
--  ── NOTE on the "notes" column collision ──
--  quote_requests ALREADY has a TEXT column called "notes" (the customer's
--  access / free-text notes from the public form — api/quote.js writes it).
--  We therefore keep internal staff notes in a SEPARATE jsonb column called
--  "admin_notes" so the two never collide.
-- ════════════════════════════════════════════════════════════

-- ── Base leads table (written by the PUBLIC quote form, api/quote.js) ──
CREATE TABLE IF NOT EXISTS quote_requests (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name          text,
  phone         text,
  email         text,
  service       text,
  from_postcode text,
  to_postcode   text,
  property_size text,
  move_date     text,
  notes         text
);

-- ── Extend the public-form table ──
ALTER TABLE quote_requests
  ADD COLUMN IF NOT EXISTS status      text DEFAULT 'new',
  ADD COLUMN IF NOT EXISTS admin_notes jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS updated_at  timestamptz DEFAULT now(),
  ADD COLUMN IF NOT EXISTS value       numeric(10,2),
  ADD COLUMN IF NOT EXISTS address     text,
  ADD COLUMN IF NOT EXISTS costs       jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS created_at  timestamptz DEFAULT now();

UPDATE quote_requests SET status = 'new' WHERE status IS NULL;

CREATE INDEX IF NOT EXISTS quote_requests_status_idx ON quote_requests (status);

-- ── Appointments / bookings ──
-- lead_id is intentionally NOT a foreign key: the existing quote_requests
-- table may lack a guaranteed unique/PK constraint usable as an FK target.
-- The application manages the relation.
CREATE TABLE IF NOT EXISTS appointments (
  id               uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  lead_id          bigint NOT NULL,
  type             text NOT NULL CHECK (type IN ('survey','move','packing')),
  scheduled_for    timestamptz NOT NULL,
  duration_minutes int NOT NULL DEFAULT 60,
  address          text,
  notes            text,
  gcal_event_id    text,
  email_sent       boolean DEFAULT false,
  created_at       timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS appointments_lead_idx ON appointments (lead_id);

-- ── Call reminders ─────────────────────────────────────────
-- A daily Vercel cron (/api/admin/reminders-run) emails you when remind_on
-- arrives. RLS stays OFF (same anon-key reasoning as above).
CREATE TABLE IF NOT EXISTS reminders (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  lead_id       bigint NOT NULL,
  remind_on     date NOT NULL,
  remind_time   text,               -- HH:MM (local UK time) you chose
  note          text,
  gcal_event_id text,               -- the "Call …" Google Calendar event
  sent          boolean DEFAULT false,
  sent_at       timestamptz,
  created_at    timestamptz DEFAULT now()
);

-- If the reminders table already exists from an earlier version, add the
-- new columns (safe to run repeatedly):
ALTER TABLE reminders
  ADD COLUMN IF NOT EXISTS remind_time   text,
  ADD COLUMN IF NOT EXISTS gcal_event_id text;

CREATE INDEX IF NOT EXISTS reminders_due_idx  ON reminders (remind_on, sent);
CREATE INDEX IF NOT EXISTS reminders_lead_idx ON reminders (lead_id);

-- ── Activity log: who added / updated / deleted what ──
-- Server-only access (anon key never ships to the browser), so RLS stays off.
create table if not exists activity_log (
  id uuid primary key default gen_random_uuid(),
  at timestamptz not null default now(),
  actor text not null default 'unknown',
  action text not null default '',
  lead_id text,
  lead_name text default '',
  detail text default ''
);
alter table activity_log disable row level security;


-- ── Migration (2026-08-13): allow packing day bookings ──
-- Run this if the appointments table was created before packing existed:
--   alter table appointments drop constraint appointments_type_check;
--   alter table appointments add constraint appointments_type_check
--     check (type in ('survey', 'move', 'packing'));

-- ── Migration (2026-08-19): job cost allocation ──
-- Line-item costs per job: [{"label":"Crew wages","amount":180}, ...]
-- Run once: alter table quote_requests add column if not exists costs jsonb default '[]';

-- ── Marketing: sold-STC leaflet drops (2026-10-04) ──
-- Every Rightmove listing in the Medway/Maidstone districts, refreshed weekly
-- by the /api/admin/marketing cron, plus Zoopla-only listings read from the
-- support@ alert emails. The admin Marketing tab shows the recent Sold STC /
-- Under offer ones. Server-only access, so RLS stays off.
create table if not exists marketing_listings (
  id            text primary key,          -- 'rm-<rightmove id>' or 'zp-<zoopla id>'
  source        text not null default 'rightmove',  -- rightmove | zoopla | both
  rightmove_id  text,
  zoopla_id     text,
  status        text not null default '',  -- '' (available) | 'Sold STC' | 'Under offer'
  address       text,
  district      text,
  area          text,
  lat           double precision,
  lng           double precision,
  beds          int,
  prop_type     text,
  price         text,
  price_num     int,
  agent         text,
  photo         text,
  rightmove_url text,
  zoopla_url    text,
  listed_on     date,
  last_change   date,
  stc_seen_on   date,                      -- first run that saw it flip to STC (exact to the week)
  stc_estimate  date,                      -- listed / re-priced date when the flip wasn't observed
  stc_date      date,                      -- coalesce(stc_seen_on, stc_estimate): sort key
  first_seen    timestamptz default now(),
  last_seen     timestamptz default now(),
  done          boolean not null default false,
  done_at       timestamptz,
  done_by       text
);
alter table marketing_listings disable row level security;
create index if not exists marketing_listings_stc_idx on marketing_listings (stc_date desc) where status <> '';
create index if not exists marketing_listings_seen_idx on marketing_listings (last_seen);

create table if not exists marketing_runs (
  id        uuid primary key default gen_random_uuid(),
  ran_at    timestamptz not null default now(),
  listings  int default 0,
  stc       int default 0,
  new_stc   int default 0,
  zoopla    int default 0,
  merged    int default 0,
  note      text default ''
);
alter table marketing_runs disable row level security;

-- ── Migration (2026-10-04): fold duplicate listings into one door ──
alter table marketing_listings
  add column if not exists dup_of     text,
  add column if not exists dupe_links jsonb not null default '[]'::jsonb;
create index if not exists marketing_listings_dup_idx on marketing_listings (dup_of);
